name: Cypress Tests

on:
  push:
    branches:
      - main
    paths:
      - 'cypress/integration/e2e/**'
      - 'cypress/integration/api/**'
  schedule:
    - cron: '0 3 * * 0' # Runs every Sunday at 3 AM UTC

jobs:
  e2e-and-api-tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: |
            cypress/integration/e2e/**/*.spec.js
            cypress/integration/api/**/*.spec.js
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

  visual-tests:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/integration/visual/**/*.spec.js
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}