name: Cypress Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 0' # Runs every Sunday at 3 AM UTC
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: false
        default: 'e2e-and-api'
        type: choice
        options:
          - e2e-and-api
          - visual
          - all

jobs:
  e2e-and-api-tests:
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'workflow_dispatch' && 
       (github.event.inputs.test_type == 'e2e-and-api' || github.event.inputs.test_type == 'all'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run
          spec: |
            cypress/integration/e2e/**/*.spec.js
            cypress/integration/api/**/*.spec.js
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

  visual-tests:
    if: |
      github.event_name == 'schedule' || 
      (github.event_name == 'workflow_dispatch' && 
       (github.event.inputs.test_type == 'visual' || github.event.inputs.test_type == 'all'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run
          spec: cypress/integration/visual/**/*.spec.js
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}